6\domain-model : Domain Model für die Klassen User und Payment erstellt
SJ2324-5BHIF-Vogi/Payment pull request #7
Opened 2023-10-09 10:15 UTC by Lindor-Limani

2023-10-09 11:11 UTC, Flayyser approved these changes
sieht gut aus

2023-10-09 13:44 UTC, LuckyForce requested changes

2023-10-09 13:44 UTC, LuckyForce commented on Spg.Payment/src/Spg.Payment.DomainModel/Model/Payment.cs
> +        private PaifForWahtEnum PaidForWhat { get; set; } = PaifForWahtEnum.None;
Typo PaidForWhatEnum

2023-10-16 10:04 UTC, LuckyForce commented on Spg.Payment/src/Spg.Payment.DomainModel/Model/Payment.cs
> +enum PaifForWahtEnum
Also Typo here

2023-10-16 10:04 UTC, LuckyForce commented on Spg.Payment/src/Spg.Payment.DomainModel/Model/Payment.cs
> +        public float Discount { get; set; }
```suggestion
        public int Discount { get; set; }
```

2023-10-16 10:04 UTC, LuckyForce commented on Spg.Payment/src/Spg.Payment.DomainModel/Model/Payment.cs
> +        public float Price { get; set; }
```suggestion
        public int Price { get; set; }
```

2023-10-16 10:06 UTC, LuckyForce requested changes

2023-10-16 10:06 UTC, LuckyForce commented on Spg.Payment/src/Spg.Payment.DomainModel/Model/Payment.cs
> +enum PaifForWahtEnum
```suggestion
enum PaidForWhatEnum
```

2023-10-16 10:06 UTC, LuckyForce commented on Spg.Payment/src/Spg.Payment.DomainModel/Model/Payment.cs
> +        private PaifForWahtEnum PaidForWhat { get; set; } = PaifForWahtEnum.None;
```suggestion
        private PaidForWhatEnum PaidForWhat { get; set; } = PaidForWhatEnum.None;
```

2023-11-05 13:27 UTC, LuckyForce approved these changes
Now it is good

2023-11-05 13:27 UTC, merged